(function () {
  'use strict';
  const db = window.supabaseClient;
  if (!db) return;
  const state = { prices: [], customers: [], orders: [], items: [], messages: [], settings: {}, faqs: [] };
  const el = (id) => document.getElementById(id);
  const money = (n) => `NGN ${Number(n || 0).toLocaleString('en-NG')}`;
  const text = (id, value) => { if (el(id)) el(id).textContent = value; };
  const message = (value, error) => { let node = el('ops-feedback'); if (!node) { node = document.createElement('p'); node.id = 'ops-feedback'; node.className = 'admin-feedback'; el('dashboard')?.prepend(node); } node.textContent = value; node.dataset.error = error ? 'true' : 'false'; };
  async function profile() { const { data } = await db.auth.getSession(); const email = data.session?.user.email; if (!email) return { session: null, profile: null }; const result = await db.from('users').select('id,email').eq('email', email).maybeSingle(); return { session: data.session, profile: result.data }; }
  async function audit(action, type, id, oldValue, newValue) { const current = await profile(); await db.from('audit_logs').insert({ admin_id: current.profile?.id || null, admin_email: current.session?.user.email, action, entity_type: type, entity_id: String(id || ''), old_value: oldValue || null, new_value: newValue || null }); }
  async function load() {
    const results = await Promise.all([
      db.from('prices').select('*').order('id'), db.from('customers').select('*').order('created_at', { ascending: false }),
      db.from('orders').select('*, customers(full_name, phone)').order('created_at', { ascending: false }), db.from('order_items').select('*').order('created_at'),
      db.from('messages').select('*').order('id', { ascending: false }), db.from('business_settings').select('*'), db.from('faqs').select('*').order('sort_order'), db.from('audit_logs').select('*').order('created_at', { ascending: false }).limit(100)
    ]);
    const bad = results.find((r) => r.error); if (bad) throw bad.error;
    state.prices = results[0].data || []; state.customers = results[1].data || []; state.orders = results[2].data || []; state.items = results[3].data || [];
    state.messages = results[4].data || []; state.settings = Object.fromEntries((results[5].data || []).map((r) => [r.key, r.value])); state.faqs = results[6].data || [];
    render(results[7].data || []); fillPriceSelect();
  }
  function render(audits) {
    text('metric-prices', state.prices.length); text('metric-messages', state.messages.filter((m) => !m.is_replied).length);
    const now = new Date(), day = new Date(now.getFullYear(), now.getMonth(), now.getDate()), month = new Date(now.getFullYear(), now.getMonth(), 1);
    const today = state.orders.filter((o) => new Date(o.created_at) >= day), monthly = state.orders.filter((o) => new Date(o.created_at) >= month);
    text('metric-today-orders', today.length); text('metric-ready-orders', state.orders.filter((o) => o.status === 'ready').length);
    text('metric-revenue-today', money(today.reduce((n, o) => n + Number(o.total), 0))); text('metric-revenue-month', money(monthly.reduce((n, o) => n + Number(o.total), 0)));
    renderCustomers(); renderOrders(); renderSettings(); renderFaqs(); renderAudits(audits);
    const popular = {}; state.items.forEach((i) => { popular[i.item_name] = (popular[i.item_name] || 0) + Number(i.quantity); }); const list = el('popular-services');
    if (list) { list.textContent = ''; Object.entries(popular).sort((a, b) => b[1] - a[1]).slice(0, 5).forEach(([name, qty]) => { const li = document.createElement('li'); li.textContent = `${name}: ${qty} items`; list.appendChild(li); }); }
  }
  function rowValues(row, values) { values.forEach((value) => { const cell = row.insertCell(); cell.textContent = String(value ?? ''); }); }
  function renderCustomers() { const body = el('customers-table-body'); if (!body) return; body.textContent = ''; const q = (el('customer-search')?.value || '').toLowerCase(); state.customers.filter((c) => `${c.full_name} ${c.phone} ${c.email}`.toLowerCase().includes(q)).forEach((c) => { const row = body.insertRow(); rowValues(row, [c.full_name, c.phone, c.email, c.total_orders, c.notes]); }); }
  function renderOrders() { const body = el('orders-table-body'); if (!body) return; body.textContent = ''; const q = (el('order-search')?.value || '').toLowerCase(); state.orders.filter((o) => `${o.ticket_number} ${o.customers?.full_name} ${o.customers?.phone} ${o.status}`.toLowerCase().includes(q)).forEach((o) => { const row = body.insertRow(); rowValues(row, [o.ticket_number, o.customers?.full_name, o.customers?.phone, o.status, money(o.total), money(Number(o.total) - Number(o.amount_paid)), o.payment_status, o.expected_collection_at ? new Date(o.expected_collection_at).toLocaleString() : '']); const cell = row.insertCell(); const select = document.createElement('select'); ['received','washing','ironing','packaging','ready','collected','cancelled'].forEach((s) => select.add(new Option(s, s))); select.value = o.status; select.onchange = () => updateOrder(o, { status: select.value, ready_at: select.value === 'ready' ? new Date().toISOString() : o.ready_at, collected_at: select.value === 'collected' ? new Date().toISOString() : o.collected_at, amount_paid: select.value === 'collected' ? o.total : o.amount_paid, payment_status: select.value === 'collected' ? 'paid' : o.payment_status }); cell.appendChild(select); const notify = document.createElement('button'); notify.textContent = 'Notify Customer'; notify.onclick = () => notifyCustomer(o); cell.appendChild(notify); }); }
  function renderSettings() { if (el('setting-hours')) el('setting-hours').value = state.settings.business_hours || ''; if (el('setting-payment')) el('setting-payment').value = state.settings.payment_instructions || ''; if (el('setting-whatsapp')) el('setting-whatsapp').value = state.settings.whatsapp_number || ''; }
  function renderFaqs() { const body = el('faq-table-body'); if (!body) return; body.textContent = ''; state.faqs.forEach((f) => { const row = body.insertRow(); rowValues(row, [f.question, f.answer, f.sort_order, f.is_active ? 'Active' : 'Hidden']); const cell = row.insertCell(); const button = document.createElement('button'); button.textContent = f.is_active ? 'Hide' : 'Show'; button.onclick = () => saveFaq(f, { is_active: !f.is_active }); cell.appendChild(button); }); }
  function renderAudits(rows) { const body = el('audit-table-body'); if (!body) return; body.textContent = ''; rows.forEach((a) => { const row = body.insertRow(); rowValues(row, [new Date(a.created_at).toLocaleString(), a.admin_email, a.action, a.entity_type, a.entity_id]); }); }
  function fillPriceSelect() { const select = el('order-price-select'); if (!select) return; select.textContent = ''; state.prices.forEach((p) => select.add(new Option(`${p.cloth_type} - ${money(p.washing_price)}`, p.id))); }
  function totals() { const subtotal = (state.pending || []).reduce((n, i) => n + i.line_total, 0), discount = Number(el('order-discount')?.value || 0), total = Math.max(0, subtotal - discount), paid = Number(el('order-paid')?.value || 0); text('order-subtotal', money(subtotal)); text('order-total', money(total)); text('order-payment-status', paid >= total && total ? 'paid' : paid ? 'partial' : 'unpaid'); return { subtotal, discount, total, paid }; }
  function renderPending() { const list = el('order-item-list'); if (!list) return; list.textContent = ''; (state.pending || []).forEach((i, index) => { const li = document.createElement('li'); li.textContent = `${i.item_name} x ${i.quantity} = ${money(i.line_total)}`; const button = document.createElement('button'); button.textContent = 'Remove'; button.onclick = () => { state.pending.splice(index, 1); renderPending(); totals(); }; li.appendChild(button); list.appendChild(li); }); }  async function updateOrder(order, changes) { if (changes.status === 'collected') { const current = await profile(); changes.collected_by = current.profile?.id || null; } const { error } = await db.from('orders').update(changes).eq('id', order.id); if (error) return message(error.message, true); await audit('Updated order', 'order', order.id, order, changes); await load(); message('Order updated.'); }
  async function notifyCustomer(order) { const balance = Math.max(0, Number(order.total) - Number(order.amount_paid)); const note = `Hello ${order.customers?.full_name || 'Customer'}, your laundry order ${order.ticket_number} is ready for collection. Your outstanding balance is ${money(balance)}. You can collect during our business hours.`; try { await navigator.clipboard.writeText(note); message('Notification copied. Paste it into WhatsApp.'); } catch { window.prompt('Copy notification:', note); } }
  async function saveFaq(faq, changes) { const { error } = await db.from('faqs').update(changes).eq('id', faq.id); if (error) return message(error.message, true); await audit('Updated FAQ', 'faq', faq.id, faq, changes); await load(); }
  function exportCsv(filename, rows) { if (!rows.length) return message('Nothing to export.'); const keys = Object.keys(rows[0]); const csv = [keys.join(','), ...rows.map((r) => keys.map((k) => String(r[k] ?? '').replaceAll(',', ' ')).join(','))].join(String.fromCharCode(10)); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
  function bind() {
    state.pending = [];
    el('customer-search')?.addEventListener('input', renderCustomers); el('order-search')?.addEventListener('input', renderOrders); el('order-discount')?.addEventListener('input', totals); el('order-paid')?.addEventListener('input', totals);
    el('add-order-item')?.addEventListener('click', () => { const price = state.prices.find((p) => String(p.id) === el('order-price-select').value); if (!price) return; const quantity = Math.max(1, Number(el('order-item-qty').value || 1)), service = el('order-service-type').value, unit = Number(service === 'ironing' ? price.ironing_price : price.washing_price); state.pending.push({ price_id: price.id, item_name: price.cloth_type, service_type: service, quantity, unit_price: unit, line_total: unit * quantity }); renderPending(); totals(); });
    el('customer-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const row = { full_name: el('customer-name').value.trim(), phone: el('customer-phone').value.trim(), email: el('customer-email').value.trim().toLowerCase() || null, address: el('customer-address').value.trim() || null, notes: el('customer-notes').value.trim() || null }; const { error } = await db.from('customers').upsert(row, { onConflict: 'phone' }); if (error) return message(error.message, true); event.target.reset(); await load(); message('Customer saved.'); });
    el('order-form')?.addEventListener('submit', async (event) => { event.preventDefault(); if (!state.pending.length) return message('Add at least one item first.', true); const t = totals(); let result = await db.from('customers').upsert({ full_name: el('order-customer-name').value.trim(), phone: el('order-customer-phone').value.trim(), email: el('order-customer-email').value.trim().toLowerCase() || null }, { onConflict: 'phone' }).select().single(); if (result.error) return message(result.error.message, true); const ticket = `LD-${Date.now().toString().slice(-6)}`; result = await db.from('orders').insert({ ticket_number: ticket, customer_id: result.data.id, subtotal: t.subtotal, discount: t.discount, total: t.total, amount_paid: t.paid, payment_status: t.paid >= t.total ? 'paid' : t.paid ? 'partial' : 'unpaid', created_by: (await profile()).profile?.id || null, expected_collection_at: el('order-collection-date').value ? new Date(el('order-collection-date').value).toISOString() : null, notes: el('order-notes').value.trim() }).select().single(); if (result.error) return message(result.error.message, true); const items = state.pending.map((item) => ({ ...item, order_id: result.data.id })); result = await db.from('order_items').insert(items); if (result.error) return message(result.error.message, true); await audit('Created order', 'order', result.data.id, null, { ticket_number: ticket, total: t.total }); event.target.reset(); state.pending = []; renderPending(); await load(); message(`Order ${ticket} created.`); });
    el('settings-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const rows = [['business_hours', el('setting-hours').value], ['payment_instructions', el('setting-payment').value], ['whatsapp_number', el('setting-whatsapp').value]]; for (const [key, value] of rows) { const result = await db.from('business_settings').upsert({ key, value }); if (result.error) return message(result.error.message, true); } await audit('Updated business settings', 'settings', 'business_settings', null, Object.fromEntries(rows)); await load(); message('Settings saved.'); });
    el('faq-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const { error } = await db.from('faqs').insert({ question: el('faq-question').value.trim(), answer: el('faq-answer').value.trim(), sort_order: Number(el('faq-order').value || 0) }); if (error) return message(error.message, true); event.target.reset(); await load(); message('FAQ added.'); });
    el('export-prices')?.addEventListener('click', () => exportCsv('prices.csv', state.prices)); el('export-orders')?.addEventListener('click', () => exportCsv('orders.csv', state.orders)); el('export-messages')?.addEventListener('click', async () => { const { data } = await db.from('messages').select('*').order('id', { ascending: false }); exportCsv('messages.csv', data || []); });
  }
  document.addEventListener('DOMContentLoaded', async () => { const { data } = await db.auth.getSession(); if (!data.session) return; bind(); try { await load(); } catch (error) { message(`Operations data could not load: ${error.message}`, true); } });
})();