-- Run this in the Supabase SQL editor.
-- This script creates/updates the tables and RLS rules used by the Netlify-hosted app.

create extension if not exists pgcrypto;

create table if not exists public.prices (
  id bigint generated by default as identity primary key,
  cloth_type text not null,
  ironing_price numeric not null check (ironing_price >= 0),
  washing_price numeric not null check (washing_price >= 0),
  gender text not null check (gender in ('Male', 'Female')),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 80),
  email text not null check (char_length(email) <= 120),
  message text not null check (char_length(message) <= 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key,
  username text,
  email text not null unique,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_via text,
  invited_by uuid,
  created_at timestamptz not null default now()
);

alter table public.users add column if not exists created_via text;
alter table public.users add column if not exists invited_by uuid;
alter table public.users add column if not exists created_at timestamptz not null default now();

create table if not exists public.admin_otp_requests (
  id uuid primary key default gen_random_uuid(),
  candidate_email text not null,
  otp_hash text not null,
  otp_salt text not null,
  invited_by uuid not null,
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  expires_at timestamptz not null,
  used_at timestamptz,
  invalidated_at timestamptz,
  requested_ip text,
  created_at timestamptz not null default now(),
  constraint admin_otp_attempts_check check (attempts <= max_attempts),
  constraint admin_otp_expiry_after_creation check (expires_at > created_at)
);

create index if not exists admin_otp_requests_candidate_email_idx
  on public.admin_otp_requests (candidate_email);

create index if not exists admin_otp_requests_pending_idx
  on public.admin_otp_requests (candidate_email, created_at desc)
  where used_at is null and invalidated_at is null;

create table if not exists public.admin_invite_audit (
  id bigint generated by default as identity primary key,
  event_type text not null,
  candidate_email text,
  inviting_admin_id uuid,
  ip_address text,
  outcome_detail text,
  created_at timestamptz not null default now()
);

create index if not exists admin_invite_audit_candidate_email_idx
  on public.admin_invite_audit (candidate_email, created_at desc);

create index if not exists admin_invite_audit_ip_idx
  on public.admin_invite_audit (ip_address, created_at desc);

create table if not exists public.contact_rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists contact_rate_limits_ip_created_idx
  on public.contact_rate_limits (ip_hash, created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where lower(email) = lower(auth.email())
      and role = 'admin'
  );
$$;

alter table public.prices enable row level security;
alter table public.messages enable row level security;
alter table public.users enable row level security;
alter table public.admin_otp_requests enable row level security;
alter table public.admin_invite_audit enable row level security;
alter table public.contact_rate_limits enable row level security;

-- Prices: public read, admin write.
drop policy if exists "prices public read" on public.prices;
create policy "prices public read"
on public.prices
for select
to anon, authenticated
using (true);

drop policy if exists "prices admin insert" on public.prices;
create policy "prices admin insert"
on public.prices
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "prices admin update" on public.prices;
create policy "prices admin update"
on public.prices
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "prices admin delete" on public.prices;
create policy "prices admin delete"
on public.prices
for delete
to authenticated
using (public.is_admin());

-- Messages: public insert, admin read/delete. No update policy.
drop policy if exists "messages anon insert" on public.messages;
create policy "messages anon insert"
on public.messages
for insert
to anon, authenticated
with check (true);

drop policy if exists "messages admin read" on public.messages;
create policy "messages admin read"
on public.messages
for select
to authenticated
using (public.is_admin());

drop policy if exists "messages admin delete" on public.messages;
create policy "messages admin delete"
on public.messages
for delete
to authenticated
using (public.is_admin());

-- Users: read own profile or admin-read. No browser insert/update/delete policies.
drop policy if exists "users own profile read" on public.users;
create policy "users own profile read"
on public.users
for select
to authenticated
using (lower(email) = lower(auth.email()) or public.is_admin());

-- OTP and rate-limit internals: service-role only through Netlify edge functions.
-- RLS is enabled and no anon/authenticated policies are created for these tables.
drop policy if exists "admin audit admin read" on public.admin_invite_audit;
create policy "admin audit admin read"
on public.admin_invite_audit
for select
to authenticated
using (public.is_admin());
