-- Run this in the Supabase SQL editor.
-- This script creates/updates the tables and RLS rules used by the Netlify-hosted app.

create extension if not exists pgcrypto;

create table if not exists public.prices (
  id bigint generated by default as identity primary key,
  cloth_type text not null,
  ironing_price numeric not null check (ironing_price >= 0),
  washing_price numeric not null check (washing_price >= 0),
  gender text not null check (gender in ('Male', 'Female')),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 80),
  email text not null check (char_length(email) <= 120),
  message text not null check (char_length(message) <= 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text,
  email text not null unique,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_via text,
  invited_by uuid,
  created_at timestamptz not null default now()
);

alter table public.users add column if not exists created_via text;
alter table public.users add column if not exists invited_by uuid;
alter table public.users add column if not exists created_at timestamptz not null default now();

create table if not exists public.admin_otp_requests (
  id uuid primary key default gen_random_uuid(),
  candidate_email text not null,
  otp_hash text not null,
  otp_salt text not null,
  invited_by uuid not null,
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  expires_at timestamptz not null,
  used_at timestamptz,
  invalidated_at timestamptz,
  requested_ip text,
  created_at timestamptz not null default now(),
  constraint admin_otp_attempts_check check (attempts <= max_attempts),
  constraint admin_otp_expiry_after_creation check (expires_at > created_at)
);

create index if not exists admin_otp_requests_candidate_email_idx
  on public.admin_otp_requests (candidate_email);

create index if not exists admin_otp_requests_pending_idx
  on public.admin_otp_requests (candidate_email, created_at desc)
  where used_at is null and invalidated_at is null;

create table if not exists public.admin_invite_audit (
  id bigint generated by default as identity primary key,
  event_type text not null,
  candidate_email text,
  inviting_admin_id uuid,
  ip_address text,
  outcome_detail text,
  created_at timestamptz not null default now()
);

create index if not exists admin_invite_audit_candidate_email_idx
  on public.admin_invite_audit (candidate_email, created_at desc);

create index if not exists admin_invite_audit_ip_idx
  on public.admin_invite_audit (ip_address, created_at desc);

create table if not exists public.contact_rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists contact_rate_limits_ip_created_idx
  on public.contact_rate_limits (ip_hash, created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where lower(email) = lower(auth.email())
      and role = 'admin'
  );
$$;

alter table public.prices enable row level security;
alter table public.messages enable row level security;
alter table public.users enable row level security;
alter table public.admin_otp_requests enable row level security;
alter table public.admin_invite_audit enable row level security;
alter table public.contact_rate_limits enable row level security;

-- Prices: public read, admin write.
drop policy if exists "prices public read" on public.prices;
create policy "prices public read"
on public.prices
for select
to anon, authenticated
using (true);

drop policy if exists "prices admin insert" on public.prices;
create policy "prices admin insert"
on public.prices
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "prices admin update" on public.prices;
create policy "prices admin update"
on public.prices
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "prices admin delete" on public.prices;
create policy "prices admin delete"
on public.prices
for delete
to authenticated
using (public.is_admin());

-- Messages: public insert, admin read/delete. No update policy.
drop policy if exists "messages anon insert" on public.messages;
create policy "messages anon insert"
on public.messages
for insert
to anon, authenticated
with check (true);

drop policy if exists "messages admin read" on public.messages;
create policy "messages admin read"
on public.messages
for select
to authenticated
using (public.is_admin());

drop policy if exists "messages admin delete" on public.messages;
create policy "messages admin delete"
on public.messages
for delete
to authenticated
using (public.is_admin());

-- Users: read own profile or admin-read. No browser insert/update/delete policies.
drop policy if exists "users own profile read" on public.users;
create policy "users own profile read"
on public.users
for select
to authenticated
using (lower(email) = lower(auth.email()) or public.is_admin());

-- OTP and rate-limit internals: service-role only through Netlify edge functions.
-- RLS is enabled and no anon/authenticated policies are created for these tables.
drop policy if exists "admin audit admin read" on public.admin_invite_audit;
create policy "admin audit admin read"
on public.admin_invite_audit

for select
to authenticated
using (public.is_admin());

-- In-store operations: customers, walk-in orders, settings, FAQs, and audit logs.
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null unique,
  email text,
  address text,
  notes text,
  total_orders integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  ticket_number text not null unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  status text not null default 'received' check (status in ('received', 'washing', 'ironing', 'packaging', 'ready', 'collected', 'cancelled')),
  subtotal numeric not null default 0 check (subtotal >= 0),
  discount numeric not null default 0 check (discount >= 0),
  total numeric not null default 0 check (total >= 0),
  amount_paid numeric not null default 0 check (amount_paid >= 0),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'partial', 'paid')),
  expected_collection_at timestamptz,
  ready_at timestamptz,
  collected_at timestamptz,
  collected_by bigint references public.users(id),
  notes text,
  created_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  price_id bigint references public.prices(id) on delete set null,
  item_name text not null,
  service_type text not null check (service_type in ('washing', 'ironing')),
  quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0),
  line_total numeric not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  key text primary key,
  value text not null,
  updated_by bigint references public.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint references public.users(id),
  admin_email text,
  action text not null,
  entity_type text,
  entity_id text,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

create index if not exists customers_phone_idx on public.customers (phone);
create index if not exists orders_ticket_number_idx on public.orders (ticket_number);
create index if not exists orders_customer_created_idx on public.orders (customer_id, created_at desc);
create index if not exists orders_status_created_idx on public.orders (status, created_at desc);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists audit_logs_created_idx on public.audit_logs (created_at desc);

insert into public.business_settings (key, value)
values
  ('business_hours', 'Mon-Sat: 8:00 AM - 6:00 PM'),
  ('payment_instructions', 'Payment is accepted in-store. Please confirm cash, POS, or transfer details with staff before collection.'),
  ('whatsapp_number', '2348063894359'),
  ('business_name', 'Idojuan Laundry and Dry Cleaning Services'),
  ('business_address', 'Mosque shop 7 beside Ogab Services, Gado Nasko road 2/1, Kubwa, Abuja'),
  ('business_email', 'Idoresltd@yahoo.com'),
  ('business_phone', '08063894359'),
  ('business_map_url', 'https://www.google.com/maps/search/?api=1&query=Idojuan%20Laundry%20Kubwa%20Abuja'),
  ('default_turnaround_hours', '48'),
  ('ready_notification_template', 'Hello {{customer_name}}, your laundry order {{ticket_number}} is ready for collection. Your outstanding balance is {{outstanding_balance}}. You can collect during {{business_hours}}.')
on conflict (key) do nothing;

insert into public.faqs (question, answer, sort_order)
values
  ('Do you offer pickup or delivery?', 'No. Drop-off and collection are in-store only at our Kubwa, Abuja shop.', 1),
  ('How do I check my order status?', 'Use your laundry ticket number on the website or contact us on WhatsApp.', 2),
  ('When can I collect my clothes?', 'Staff will tell you the expected collection time. You can also check your ticket status online.', 3),
  ('What payment methods are accepted?', 'Please confirm cash, POS, or transfer details with staff at the shop.', 4)
on conflict do nothing;

alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.business_settings enable row level security;
alter table public.faqs enable row level security;
alter table public.audit_logs enable row level security;

-- Public reads only safe public configuration. Operational data remains admin/service-role only.
drop policy if exists "settings public read" on public.business_settings;
create policy "settings public read"
on public.business_settings
for select
to anon, authenticated
using (key in ('business_hours', 'payment_instructions', 'whatsapp_number'));

drop policy if exists "faqs public active read" on public.faqs;
create policy "faqs public active read"
on public.faqs
for select
to anon, authenticated
using (is_active = true);

-- Admin CRUD for in-store operations.
drop policy if exists "customers admin all" on public.customers;
create policy "customers admin all"
on public.customers
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "orders admin all" on public.orders;
create policy "orders admin all"
on public.orders
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "order_items admin all" on public.order_items;
create policy "order_items admin all"
on public.order_items
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "settings admin all" on public.business_settings;
create policy "settings admin all"
on public.business_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "faqs admin all" on public.faqs;
create policy "faqs admin all"
on public.faqs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "audit logs admin read" on public.audit_logs;
create policy "audit logs admin read"
on public.audit_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "audit logs admin insert" on public.audit_logs;
create policy "audit logs admin insert"
on public.audit_logs
for insert
to authenticated
with check (public.is_admin());

create or replace function public.increment_customer_order_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.customers
  set total_orders = total_orders + 1,
      updated_at = now()
  where id = new.customer_id;
  return new;
end;
$$;

drop trigger if exists orders_increment_customer_count on public.orders;
create trigger orders_increment_customer_count
after insert on public.orders
for each row execute function public.increment_customer_order_count();

-- Message follow-up status for admin inbox.
alter table public.messages add column if not exists is_replied boolean not null default false;

drop policy if exists "messages admin update" on public.messages;
create policy "messages admin update"
on public.messages
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());
